# This is configuration for standard experiment. Please refer to config.py for more details.
name: 'FaceHuman-KD-attention'
description: >
    Default configuration for synthesis of face & human.
    Apply maxpooling to face features(query)
n_sample: 64
resolution: 256
classes:
- 'face'
- 'human'

ADA:
  enabled: true
  target: 0.6  # set 0 to fix prob.
  p: 0.0
  interval: 4
  kimg: 500
  # KWARGS:

DATASET:
  name: DeepFashion
  roots:
    - '~/data/deepfashion'
  sources:
    - 'align_1.2'
  xflip: true
  num_workers: 4
  pin_memory: true

MODEL:
  z_dim: 512
  w_dim: 512
  mode: 'joint'
  freeze_teacher: false
  teacher_weight: ''
  attn_res: 256

  MAPPING:
    num_layers: 8
    # embed_dim: 512
    # layer_dim: 512
    lrmul: 0.01
  
  SYNTHESIS:
    img_channels: 3
    bottom_res: 4
    channel_base: 16384
    pose_encoder_kwargs:
      name: HeatmapEncoder
      max_channels: 512
      heatmap_size: 256
      in_channels: 17

  DISCRIMINATOR:
    img_channels: 3
    branch_res: 256
    top_res: 4
    channel_base: 16384


TRAIN:
  iteration: 10
  batch_gpu: 8
  lrate: 0.002
  R1:
    every: 16
    gamma: 10
  PPL:
    every: 8
    gain: 2
    bs_shrink: 2
  style_mixing_prob: 0.0
  CKPT:
    path: ''
    every: 5
    max_keep: -1
  SAMPLE:
    every: 5

EVAL:
  metrics: ''
  FID:
    dataset: ''
    every: 6250
    batch_size: 8
    n_sample: 50000
    inception_cache: ''
    sample_dir: ''

